very:
  important:
    name: Юзер
    number: 42
    days:
      - понедельник
      - вторник
      - среда
      - четверг
      - пятница
    holidays:
      - 2019-01-01
      - 2019-01-07
      - 2019-02-23
      - 2019-03-08
      - 2019-05-01
      - 2019-05-09
      - 2019-05-12
      - 2019-11-04